// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/postview/postview.proto

package postview

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPostRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d493abf9d07462f8, []int{0}
}

func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(m, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetPostResponse struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostResponse) Reset()         { *m = GetPostResponse{} }
func (m *GetPostResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostResponse) ProtoMessage()    {}
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d493abf9d07462f8, []int{1}
}

func (m *GetPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostResponse.Unmarshal(m, b)
}
func (m *GetPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostResponse.Marshal(b, m, deterministic)
}
func (m *GetPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostResponse.Merge(m, src)
}
func (m *GetPostResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostResponse.Size(m)
}
func (m *GetPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostResponse proto.InternalMessageInfo

func (m *GetPostResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type Post struct {
	Title                string               `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Token                string               `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Thumbnail            string               `protobuf:"bytes,4,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Contact              *Contact             `protobuf:"bytes,5,opt,name=contact,proto3" json:"contact,omitempty"`
	PublishedAt          *timestamp.Timestamp `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	CategorySlugs        []string             `protobuf:"bytes,7,rep,name=category_slugs,json=categorySlugs,proto3" json:"category_slugs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_d493abf9d07462f8, []int{2}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Post) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Post) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

func (m *Post) GetContact() *Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

func (m *Post) GetPublishedAt() *timestamp.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

func (m *Post) GetCategorySlugs() []string {
	if m != nil {
		return m.CategorySlugs
	}
	return nil
}

type Contact struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Chat                 bool     `protobuf:"varint,4,opt,name=chat,proto3" json:"chat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_d493abf9d07462f8, []int{3}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Contact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Contact) GetChat() bool {
	if m != nil {
		return m.Chat
	}
	return false
}

func init() {
	proto.RegisterType((*GetPostRequest)(nil), "postview.GetPostRequest")
	proto.RegisterType((*GetPostResponse)(nil), "postview.GetPostResponse")
	proto.RegisterType((*Post)(nil), "postview.Post")
	proto.RegisterType((*Contact)(nil), "postview.Contact")
}

func init() { proto.RegisterFile("api/postview/postview.proto", fileDescriptor_d493abf9d07462f8) }

var fileDescriptor_d493abf9d07462f8 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xcf, 0x8b, 0xd4, 0x30,
	0x14, 0x66, 0x77, 0xbb, 0xdb, 0x99, 0x8c, 0x8e, 0x18, 0x3c, 0xd4, 0x51, 0x70, 0x28, 0x28, 0x0b,
	0x62, 0x8b, 0x23, 0x7a, 0x91, 0x15, 0xd4, 0x83, 0xe8, 0x49, 0xaa, 0x78, 0xf0, 0xb2, 0xbc, 0x76,
	0xdf, 0xa4, 0x61, 0xd2, 0x24, 0x36, 0xaf, 0x0e, 0x7a, 0xf7, 0xff, 0x96, 0xa4, 0xd3, 0x76, 0x04,
	0x6f, 0xf9, 0x7e, 0x34, 0xf9, 0xde, 0xf7, 0xca, 0x1e, 0x80, 0x95, 0xb9, 0x35, 0x8e, 0x7e, 0x4a,
	0xdc, 0x8f, 0x87, 0xcc, 0xb6, 0x86, 0x0c, 0x9f, 0x0d, 0x78, 0xf5, 0x48, 0x18, 0x23, 0x14, 0xe6,
	0x81, 0x2f, 0xbb, 0x6d, 0x4e, 0xb2, 0x41, 0x47, 0xd0, 0xd8, 0xde, 0x9a, 0x3e, 0x61, 0xcb, 0x0f,
	0x48, 0x9f, 0x8d, 0xa3, 0x02, 0x7f, 0x74, 0xe8, 0x88, 0xdf, 0x63, 0xe7, 0x64, 0x76, 0xa8, 0x93,
	0x93, 0xf5, 0xc9, 0xe5, 0xbc, 0xe8, 0x41, 0xfa, 0x92, 0xdd, 0x19, 0x7d, 0xce, 0x1a, 0xed, 0x90,
	0xa7, 0x2c, 0xf2, 0xef, 0x04, 0xdf, 0x62, 0xb3, 0xcc, 0xc6, 0x10, 0xc1, 0x15, 0xb4, 0xf4, 0xcf,
	0x29, 0x8b, 0x3c, 0x0c, 0xb7, 0x4a, 0x52, 0x38, 0xde, 0xea, 0x01, 0x5f, 0xb3, 0xc5, 0x0d, 0xba,
	0xaa, 0x95, 0x96, 0xa4, 0xd1, 0xc9, 0x69, 0xd0, 0x8e, 0xa9, 0x29, 0xcd, 0xd9, 0x51, 0x1a, 0xfe,
	0x90, 0xcd, 0xa9, 0xee, 0x9a, 0x52, 0x83, 0x54, 0x49, 0x14, 0x94, 0x89, 0xe0, 0x4f, 0x59, 0x5c,
	0x19, 0x4d, 0x50, 0x51, 0x72, 0x1e, 0xb2, 0xdd, 0x9d, 0xb2, 0xbd, 0xef, 0x85, 0x62, 0x70, 0xf0,
	0x2b, 0x76, 0xcb, 0x76, 0xa5, 0x92, 0xae, 0xc6, 0x9b, 0x6b, 0xa0, 0xe4, 0x22, 0x7c, 0xb1, 0xca,
	0xfa, 0xe2, 0xb2, 0xa1, 0xb8, 0xec, 0xeb, 0x50, 0x5c, 0xb1, 0x18, 0xfd, 0x6f, 0x89, 0x3f, 0x66,
	0xcb, 0x0a, 0x08, 0x85, 0x69, 0x7f, 0x5d, 0x3b, 0xd5, 0x09, 0x97, 0xc4, 0xeb, 0xb3, 0xcb, 0x79,
	0x71, 0x7b, 0x60, 0xbf, 0x78, 0x32, 0xfd, 0xc8, 0xe2, 0xc3, 0xcb, 0x7e, 0x22, 0x5b, 0x1b, 0x3d,
	0x36, 0x11, 0x80, 0x67, 0xb1, 0xf1, 0xd3, 0xf4, 0x1d, 0xf4, 0x80, 0x73, 0x16, 0x55, 0x35, 0x50,
	0x18, 0x71, 0x56, 0x84, 0xf3, 0xe6, 0x13, 0x9b, 0xf9, 0x46, 0xbf, 0x49, 0xdc, 0xf3, 0x37, 0x2c,
	0x3e, 0x6c, 0x85, 0x27, 0xd3, 0x8c, 0xff, 0x2e, 0x74, 0x75, 0xff, 0x3f, 0x4a, 0xbf, 0xc2, 0x77,
	0x57, 0xdf, 0x5f, 0x0b, 0x49, 0x59, 0x05, 0x5b, 0x2c, 0xe1, 0x37, 0x40, 0x9b, 0xc9, 0x36, 0x87,
	0xb6, 0x02, 0x0d, 0x9b, 0x57, 0xcf, 0x73, 0x61, 0x14, 0x68, 0xf1, 0xac, 0x34, 0x52, 0x61, 0x6b,
	0x15, 0x10, 0xe6, 0x76, 0x27, 0xc6, 0xbf, 0xad, 0xbc, 0x08, 0xed, 0xbc, 0xf8, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x41, 0x82, 0xbe, 0x4a, 0x8d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostViewClient is the client API for PostView service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostViewClient interface {
	GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error)
}

type postViewClient struct {
	cc *grpc.ClientConn
}

func NewPostViewClient(cc *grpc.ClientConn) PostViewClient {
	return &postViewClient{cc}
}

func (c *postViewClient) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error) {
	out := new(GetPostResponse)
	err := c.cc.Invoke(ctx, "/postview.PostView/GetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostViewServer is the server API for PostView service.
type PostViewServer interface {
	GetPost(context.Context, *GetPostRequest) (*GetPostResponse, error)
}

func RegisterPostViewServer(s *grpc.Server, srv PostViewServer) {
	s.RegisterService(&_PostView_serviceDesc, srv)
}

func _PostView_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostViewServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postview.PostView/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostViewServer).GetPost(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostView_serviceDesc = grpc.ServiceDesc{
	ServiceName: "postview.PostView",
	HandlerType: (*PostViewServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPost",
			Handler:    _PostView_GetPost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/postview/postview.proto",
}
