// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/appdetail/appdetail.proto

package appdetail

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAppDetailRequest struct {
	PackageName          string   `protobuf:"bytes,1,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppDetailRequest) Reset()         { *m = GetAppDetailRequest{} }
func (m *GetAppDetailRequest) String() string { return proto.CompactTextString(m) }
func (*GetAppDetailRequest) ProtoMessage()    {}
func (*GetAppDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47a2272787c7138f, []int{0}
}

func (m *GetAppDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppDetailRequest.Unmarshal(m, b)
}
func (m *GetAppDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppDetailRequest.Marshal(b, m, deterministic)
}
func (m *GetAppDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppDetailRequest.Merge(m, src)
}
func (m *GetAppDetailRequest) XXX_Size() int {
	return xxx_messageInfo_GetAppDetailRequest.Size(m)
}
func (m *GetAppDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppDetailRequest proto.InternalMessageInfo

func (m *GetAppDetailRequest) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

type GetAppDetailReply struct {
	Detail               *App     `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	StatusCode           int32    `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppDetailReply) Reset()         { *m = GetAppDetailReply{} }
func (m *GetAppDetailReply) String() string { return proto.CompactTextString(m) }
func (*GetAppDetailReply) ProtoMessage()    {}
func (*GetAppDetailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_47a2272787c7138f, []int{1}
}

func (m *GetAppDetailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppDetailReply.Unmarshal(m, b)
}
func (m *GetAppDetailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppDetailReply.Marshal(b, m, deterministic)
}
func (m *GetAppDetailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppDetailReply.Merge(m, src)
}
func (m *GetAppDetailReply) XXX_Size() int {
	return xxx_messageInfo_GetAppDetailReply.Size(m)
}
func (m *GetAppDetailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppDetailReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppDetailReply proto.InternalMessageInfo

func (m *GetAppDetailReply) GetDetail() *App {
	if m != nil {
		return m.Detail
	}
	return nil
}

func (m *GetAppDetailReply) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

type App struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Homepage             string   `protobuf:"bytes,3,opt,name=homepage,proto3" json:"homepage,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	AuthorName           string   `protobuf:"bytes,5,opt,name=authorName,proto3" json:"authorName,omitempty"`
	CategoryName         string   `protobuf:"bytes,6,opt,name=categoryName,proto3" json:"categoryName,omitempty"`
	Package              *Package `protobuf:"bytes,7,opt,name=package,proto3" json:"package,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_47a2272787c7138f, []int{2}
}

func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *App) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *App) GetHomepage() string {
	if m != nil {
		return m.Homepage
	}
	return ""
}

func (m *App) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *App) GetAuthorName() string {
	if m != nil {
		return m.AuthorName
	}
	return ""
}

func (m *App) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

func (m *App) GetPackage() *Package {
	if m != nil {
		return m.Package
	}
	return nil
}

type Package struct {
	PackageId            uint32   `protobuf:"varint,1,opt,name=packageId,proto3" json:"packageId,omitempty"`
	PackageHash          string   `protobuf:"bytes,2,opt,name=packageHash,proto3" json:"packageHash,omitempty"`
	VersionCode          uint32   `protobuf:"varint,3,opt,name=versionCode,proto3" json:"versionCode,omitempty"`
	VersionName          string   `protobuf:"bytes,4,opt,name=versionName,proto3" json:"versionName,omitempty"`
	MinimumSDKVersion    string   `protobuf:"bytes,5,opt,name=minimumSDKVersion,proto3" json:"minimumSDKVersion,omitempty"`
	Permissions          []string `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Package) Reset()         { *m = Package{} }
func (m *Package) String() string { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()    {}
func (*Package) Descriptor() ([]byte, []int) {
	return fileDescriptor_47a2272787c7138f, []int{3}
}

func (m *Package) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Package.Unmarshal(m, b)
}
func (m *Package) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Package.Marshal(b, m, deterministic)
}
func (m *Package) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Package.Merge(m, src)
}
func (m *Package) XXX_Size() int {
	return xxx_messageInfo_Package.Size(m)
}
func (m *Package) XXX_DiscardUnknown() {
	xxx_messageInfo_Package.DiscardUnknown(m)
}

var xxx_messageInfo_Package proto.InternalMessageInfo

func (m *Package) GetPackageId() uint32 {
	if m != nil {
		return m.PackageId
	}
	return 0
}

func (m *Package) GetPackageHash() string {
	if m != nil {
		return m.PackageHash
	}
	return ""
}

func (m *Package) GetVersionCode() uint32 {
	if m != nil {
		return m.VersionCode
	}
	return 0
}

func (m *Package) GetVersionName() string {
	if m != nil {
		return m.VersionName
	}
	return ""
}

func (m *Package) GetMinimumSDKVersion() string {
	if m != nil {
		return m.MinimumSDKVersion
	}
	return ""
}

func (m *Package) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func init() {
	proto.RegisterType((*GetAppDetailRequest)(nil), "appdetail.GetAppDetailRequest")
	proto.RegisterType((*GetAppDetailReply)(nil), "appdetail.GetAppDetailReply")
	proto.RegisterType((*App)(nil), "appdetail.App")
	proto.RegisterType((*Package)(nil), "appdetail.Package")
}

func init() { proto.RegisterFile("api/appdetail/appdetail.proto", fileDescriptor_47a2272787c7138f) }

var fileDescriptor_47a2272787c7138f = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0xab, 0xd3, 0x40,
	0x10, 0xc6, 0x89, 0x79, 0x4d, 0xcd, 0xb4, 0x2a, 0x1d, 0x3d, 0x84, 0xc7, 0xf3, 0x11, 0x73, 0x90,
	0x77, 0x78, 0xb4, 0x50, 0x2f, 0x5e, 0xab, 0x05, 0x15, 0x45, 0x24, 0x82, 0xa0, 0x1e, 0x64, 0x6d,
	0x96, 0x74, 0x69, 0x37, 0x3b, 0x66, 0x37, 0x42, 0xff, 0x58, 0xf1, 0x5f, 0x91, 0x4c, 0xd2, 0x66,
	0x8b, 0x7a, 0xdb, 0xf9, 0x7d, 0xb3, 0xbb, 0xf3, 0x0d, 0x1f, 0x3c, 0x16, 0xa4, 0x16, 0x82, 0xa8,
	0x90, 0x4e, 0xa8, 0xfd, 0x70, 0x9a, 0x53, 0x6d, 0x9c, 0xc1, 0xf8, 0x04, 0xb2, 0xe7, 0xf0, 0xf0,
	0x95, 0x74, 0x2b, 0xa2, 0x35, 0xd7, 0xb9, 0xfc, 0xd1, 0x48, 0xeb, 0xf0, 0x09, 0x4c, 0x49, 0x6c,
	0x76, 0xa2, 0x94, 0xdf, 0x2a, 0xa1, 0x65, 0x12, 0xa4, 0xc1, 0x4d, 0x9c, 0x4f, 0x7a, 0xf6, 0x5e,
	0x68, 0x99, 0x7d, 0x85, 0xd9, 0xf9, 0x4d, 0xda, 0x1f, 0xf0, 0x29, 0x44, 0xdd, 0xc3, 0x7c, 0x63,
	0xb2, 0xbc, 0x3f, 0x1f, 0xfe, 0x5e, 0x11, 0xe5, 0xbd, 0x8a, 0xd7, 0x00, 0xd6, 0x09, 0xd7, 0xd8,
	0x97, 0xa6, 0x90, 0xc9, 0x9d, 0x34, 0xb8, 0x19, 0xe5, 0x1e, 0xc9, 0x7e, 0x07, 0x10, 0xae, 0x88,
	0x10, 0xe1, 0xc2, 0xfb, 0x9f, 0xcf, 0x98, 0xc2, 0xa4, 0x90, 0x76, 0x53, 0x2b, 0x72, 0xca, 0x54,
	0x7c, 0x39, 0xce, 0x7d, 0x84, 0x97, 0x70, 0x77, 0x6b, 0xb4, 0x24, 0x51, 0xca, 0x24, 0x64, 0xf9,
	0x54, 0xe3, 0x23, 0x18, 0x49, 0xdd, 0x0e, 0x78, 0xc1, 0x42, 0x57, 0xb4, 0xf3, 0x88, 0xc6, 0x6d,
	0x4d, 0xdd, 0x5a, 0x4b, 0x46, 0x2c, 0x79, 0x04, 0x33, 0x98, 0x6e, 0x84, 0x93, 0xa5, 0xa9, 0x0f,
	0xdc, 0x11, 0x71, 0xc7, 0x19, 0xc3, 0x5b, 0x18, 0xf7, 0xfb, 0x49, 0xc6, 0x6c, 0x1e, 0x3d, 0xf3,
	0x1f, 0x3a, 0x25, 0x3f, 0xb6, 0x64, 0xbf, 0x02, 0x18, 0xf7, 0x10, 0xaf, 0x20, 0xee, 0xf1, 0x9b,
	0x82, 0xad, 0xde, 0xcb, 0x07, 0xd0, 0xfa, 0xed, 0x8b, 0xd7, 0xc2, 0x6e, 0x8f, 0x7e, 0x3d, 0xd4,
	0x76, 0xfc, 0x94, 0xb5, 0x55, 0xa6, 0xe2, 0x75, 0x86, 0xfc, 0x82, 0x8f, 0xbc, 0x0e, 0x1e, 0xbf,
	0xf3, 0xee, 0x23, 0xbc, 0x85, 0x99, 0x56, 0x95, 0xd2, 0x8d, 0xfe, 0xb8, 0x7e, 0xfb, 0xa9, 0x13,
	0xfa, 0x45, 0xfc, 0x2d, 0xf0, 0x4c, 0xb2, 0xd6, 0xca, 0xb6, 0x95, 0x4d, 0xa2, 0x34, 0xe4, 0x99,
	0x06, 0xb4, 0xfc, 0x0c, 0xf1, 0x29, 0x1b, 0xf8, 0x0e, 0xa6, 0x7e, 0x56, 0xf0, 0xda, 0xdb, 0xcc,
	0x3f, 0xe2, 0x77, 0x79, 0xf5, 0x5f, 0x9d, 0xf6, 0x87, 0x17, 0xb3, 0x2f, 0x0f, 0xe6, 0x0b, 0xda,
	0x95, 0x43, 0xae, 0xbf, 0x47, 0x1c, 0xec, 0x67, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x71, 0xe2,
	0xab, 0xfa, 0xf9, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppDetailClient is the client API for AppDetail service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppDetailClient interface {
	GetAppDetail(ctx context.Context, in *GetAppDetailRequest, opts ...grpc.CallOption) (*GetAppDetailReply, error)
}

type appDetailClient struct {
	cc *grpc.ClientConn
}

func NewAppDetailClient(cc *grpc.ClientConn) AppDetailClient {
	return &appDetailClient{cc}
}

func (c *appDetailClient) GetAppDetail(ctx context.Context, in *GetAppDetailRequest, opts ...grpc.CallOption) (*GetAppDetailReply, error) {
	out := new(GetAppDetailReply)
	err := c.cc.Invoke(ctx, "/appdetail.AppDetail/GetAppDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppDetailServer is the server API for AppDetail service.
type AppDetailServer interface {
	GetAppDetail(context.Context, *GetAppDetailRequest) (*GetAppDetailReply, error)
}

// UnimplementedAppDetailServer can be embedded to have forward compatible implementations.
type UnimplementedAppDetailServer struct {
}

func (*UnimplementedAppDetailServer) GetAppDetail(ctx context.Context, req *GetAppDetailRequest) (*GetAppDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppDetail not implemented")
}

func RegisterAppDetailServer(s *grpc.Server, srv AppDetailServer) {
	s.RegisterService(&_AppDetail_serviceDesc, srv)
}

func _AppDetail_GetAppDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppDetailServer).GetAppDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appdetail.AppDetail/GetAppDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppDetailServer).GetAppDetail(ctx, req.(*GetAppDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppDetail_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appdetail.AppDetail",
	HandlerType: (*AppDetailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppDetail",
			Handler:    _AppDetail_GetAppDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/appdetail/appdetail.proto",
}
